[package]
name = "rustyriscy"
version = "0.1.0"
authors = ["Nashe Mncube <mncubenashe@gmail.com>"]
edition = "2018"

[dependencies]
spin = "0.5.2"
volatile = "0.2.6"
qemu-exit = "^1"
[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
